name: Docker Image CI

on:
  push:
    tags:
    - "*" # Running this workflow for any tag


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Build and publish Docker Images to GitHub Container registry
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.DOCKER_PUBLISH }}
        image-name: docker.pkg.github.com/${{ github.repository }}/status:test
        image-tag: ${{ steps.get_version.outputs.VERSION }}
        additional-image-tags: latest
        extract-git-tag: true # Provide flag to extract Docker image tag from git reference
